name: Test
on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04
    name: Go 1.23
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Setup go-acc
        run: go install github.com/ory/go-acc@latest

      - name: Setup gotestfmt
        uses: haveyoudebuggedit/gotestfmt-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run test
        run: |
          TEST_BENCH_OPTION="-bench=."

          set -euo pipefail
          go-acc -o cover.out ./... -- \
            ${TEST_BENCH_OPTION} \
            -json \
            -v -race 2>&1 | grep -v '^go: downloading' | tee /tmp/gotest.log | gotestfmt

      - name: Upload test log
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-log
          path: /tmp/gotest.log
          if-no-files-found: error

      - uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          flags: go
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
