name: Lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint-go:
    name: Go Lint
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-24.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - uses: actions/checkout@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.63.4
